db:
  image: postgres:9.4
  environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

api:
    extends:
        file: dcenv/common.yml
        service: api
    command: python3 manage.py runserver 0.0.0.0:5000
    volumes:
        - .:/code:rw
    links:
        - db
    env_file:
        - ./dcenv/dev.txt
